#### Project and File Setup{.tabset}
<h2>Project and File Setup</h2>
First thing we're going to do is start an R project for this training and set up the same file structure, which we'll continue to use all summer. To set up a project, open R Studio and go to: </br> </br><div style="text-indent:20px"> <h3>File > New Project > New Directory > New Project</h3></div></br> 
Find the directory you're going to work from (other than avoiding saving to your desktop, anywhere is probably fine), and name the directory the R_training. 

<p class='code'>Now run the code chunk below to set up the same file structure.</p> 

```{r, c3, echo=TRUE}
# Step 1m 
subfolders<-c("figures", "tables", "rscripts", "shapefiles")

invisible(lapply(subfolders, function(x){
  if(!dir.exists(x)){dir.create(paste(getwd(), x, sep = '/'))}
  }))

if(!dir.exists("../data")){dir.create('../data')} # creating a data folder to store MIDN data tables if it doesn't already exist. 
```

<ul><li>This approach makes sharing code easier, because the parent directly can vary across machines, as long as the project has the same subdirectory. Note the .. before /data. That tells R to go back one level in the parent directory, so you can store your data in one place and access it more easily in the future.</li>
<li>Now that the data folder exists, download the MIDN data tables into the data folder. You can download the zip of all of the tables <a href="https://drive.google.com/file/d/1wnaR7kqxdhgXuPwwJvMjhY3bXsie_lxq/view?usp=sharing">here</a>. Once you have them unzipped in your data folder, we'll be able to load and work with them in R.</li>
<li>Once we start working on the park summaries, you'll want to create a project for each park, using its 4-letter code. Once you create a project for a given park, run the first 2 steps in the code chunk above to set up the file system within.</li>
<li>The last thing to mention here is the # in the code chunk above. The # comments out anything after it on the same line, so R knows not to try to run it. Commenting your code allows you to document what you're doing, so it's easier for someone else (or you 3 months later) to follow your code. </li></ul>
